#!/usr/bin/env python3
"""Initialize a SWFT DSL harness workspace."""

from __future__ import annotations

import argparse
from pathlib import Path

from harness_common import DEFAULT_CONFIG, create_stage_dirs, init_state, load_config, save_json

MODEL_CONFIG_TEMPLATE = {
    "model_class": "TODO_ModelClassName",
    "model_kwargs": {},
    "entry_method": "forward",
    "weights_ref": "external:torch_weights",
    "input_generation": {
        "mode": "agent_infer",
        "notes": "Stage 01 must infer model entry inputs from the configured model source, weights, and this config, then write output/input_spec.json."
    },
    "export": {
        "eval_mode": True,
        "disable_grad": True,
        "dtype_policy": "follow_checkpoint_and_input_spec"
    }
}

INPUT_PATHS_TEMPLATE = {
    "torch_model_source": "shared/model/model.py",
    "torch_model_config": "shared/model/model_config.json",
    "torch_weights": "shared/model/weights.pth",
    "similar_model_dsl": "shared/similar_dsl/similar_model_dsl.py",
    "swft_source": {
        "path": "swft_source",
        "relative_to": "harness"
    }
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", default="work")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    workspace = Path(args.workspace).resolve()
    config_path = Path(args.config).resolve()
    state_file = workspace / "pipeline_state.json"
    if state_file.exists() and not args.force:
        raise SystemExit(f"state already exists: {state_file}; use --force to reinitialize")

    config = load_config(config_path)
    workspace.mkdir(parents=True, exist_ok=True)
    create_stage_dirs(workspace, config)
    save_json(workspace / "pipeline_config.snapshot.json", config)
    save_json(state_file, init_state(workspace, config_path, config))
    model_config = workspace / "shared" / "model" / "model_config.json"
    if not model_config.exists() or args.force:
        save_json(model_config, MODEL_CONFIG_TEMPLATE)
    input_paths = workspace / "input_paths.json"
    if not input_paths.exists() or args.force:
        save_json(input_paths, INPUT_PATHS_TEMPLATE)

    readme = workspace / "README.md"
    if not readme.exists() or args.force:
        readme.write_text(
            "# Harness Workspace\n\n"
            "Place user-provided inputs anywhere under this workspace, then edit `input_paths.json` if filenames differ from the defaults.\n\n"
            "Default input path labels:\n\n"
            "- `torch_model_source`: `shared/model/model.py`\n"
            "- `torch_weights`: `shared/model/weights.pth`\n"
            "- `torch_model_config`: `shared/model/model_config.json`\n"
            "- `similar_model_dsl`: `shared/similar_dsl/similar_model_dsl.py`\n"
            "- `swft_source`: harness repo `swft_source/` (optional compiler source tree for targeted DSL debug)\n\n"
            "Fill `model_config.json` with the target model class name, constructor kwargs, and entry method. The weight file path comes from `input_paths.json` label `torch_weights`.\n"
            "`input_spec.json` is generated by stage `01_torch_export`.\n\n"
            "Check configured paths with `python3 scripts/check_inputs.py --workspace <this-workspace>` from the harness repository root.\n\n"
            "Generated stage outputs live under `stages/<stage_id>/output/`.\n",
            encoding="utf-8",
        )

    print(f"initialized workspace: {workspace}")
    print(f"current stage: {config['stages'][0]['id']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
